"""Artifact storage — serves reports generated by agents."""

import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


@dataclass
class ArtifactInfo:
    date: str
    name: str
    size_bytes: int
    modified: str
    path: str


def _reports_root() -> Path:
    return Path(os.getenv("REPORTS_DIR", "./reports")).resolve()


def list_artifacts() -> list[ArtifactInfo]:
    """List all artifacts across all date directories."""
    root = _reports_root()
    if not root.exists():
        return []

    results = []
    for day_dir in sorted(root.iterdir(), reverse=True):
        if not day_dir.is_dir():
            continue
        for file in sorted(day_dir.iterdir()):
            if file.is_file():
                stat = file.stat()
                results.append(ArtifactInfo(
                    date=day_dir.name,
                    name=file.name,
                    size_bytes=stat.st_size,
                    modified=datetime.fromtimestamp(stat.st_mtime).isoformat(),
                    path=f"{day_dir.name}/{file.name}",
                ))
    return results


def get_artifact_path(date: str, name: str) -> Path:
    """Get a safe path to an artifact. Raises ValueError on traversal attempts."""
    root = _reports_root()
    # Reject anything with path separators or traversal characters
    if "/" in date or "\\" in date or ".." in date:
        raise ValueError("invalid path: date")
    if "/" in name or "\\" in name or ".." in name:
        raise ValueError("invalid path: name")

    target = (root / date / name).resolve()
    # Ensure target is still inside root
    try:
        target.relative_to(root)
    except ValueError:
        raise ValueError("invalid path: escapes root")

    return target
