"""Artifact storage — serves reports generated by agents.

Reports are read from the local REPORTS_DIR, and — if OBSIDIAN_VAULT_PATH
is set — merged with `{vault}/reports/` so the dashboard Files tab shows
artifacts from both the Mac Mini and the PC via Obsidian Sync.
"""

import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


@dataclass
class ArtifactInfo:
    date: str
    name: str
    size_bytes: int
    modified: str
    path: str


def _reports_roots() -> list[Path]:
    """Return all report directories to scan (local + Obsidian vault if set)."""
    roots: list[Path] = [Path(os.getenv("REPORTS_DIR", "./reports")).resolve()]
    vault = os.getenv("OBSIDIAN_VAULT_PATH", "").strip()
    if vault:
        vault_reports = Path(vault).expanduser() / "reports"
        if vault_reports.exists():
            resolved = vault_reports.resolve()
            if resolved not in roots:
                roots.append(resolved)
    return roots


def list_artifacts() -> list[ArtifactInfo]:
    """List all artifacts across all date directories and all roots.

    If the same (date, name) exists in multiple roots, the most recently
    modified copy wins (so edits on either machine show through).
    """
    merged: dict[tuple[str, str], ArtifactInfo] = {}
    for root in _reports_roots():
        if not root.exists():
            continue
        for day_dir in sorted(root.iterdir(), reverse=True):
            if not day_dir.is_dir():
                continue
            for file in sorted(day_dir.iterdir()):
                if not file.is_file():
                    continue
                stat = file.stat()
                info = ArtifactInfo(
                    date=day_dir.name,
                    name=file.name,
                    size_bytes=stat.st_size,
                    modified=datetime.fromtimestamp(stat.st_mtime).isoformat(),
                    path=f"{day_dir.name}/{file.name}",
                )
                key = (info.date, info.name)
                existing = merged.get(key)
                if existing is None or info.modified > existing.modified:
                    merged[key] = info

    # Return newest date first, then filename
    return sorted(merged.values(), key=lambda a: (a.date, a.name), reverse=True)


def get_artifact_path(date: str, name: str) -> Path:
    """Get a safe path to an artifact. Raises ValueError on traversal attempts.

    Searches all configured roots (local + vault). Returns the first match
    whose resolved path stays inside its root.
    """
    # Reject anything with path separators or traversal characters
    if "/" in date or "\\" in date or ".." in date:
        raise ValueError("invalid path: date")
    if "/" in name or "\\" in name or ".." in name:
        raise ValueError("invalid path: name")

    last_candidate: Path | None = None
    for root in _reports_roots():
        target = (root / date / name).resolve()
        try:
            target.relative_to(root)
        except ValueError:
            raise ValueError("invalid path: escapes root")
        last_candidate = target
        if target.exists():
            return target

    # Preserve prior behaviour: return a path (even if missing) so callers
    # can decide how to handle 404s. Fall back to the local root.
    if last_candidate is not None:
        return last_candidate
    raise ValueError("invalid path: no roots configured")


def save_run_output(agent_id: str, job_id: int, prompt: str, output: str, status: str) -> Path | None:
    """Save an agent run's output as a markdown file in reports/{today}/.

    Returns the path if written, None if output was empty.
    """
    if not output or not output.strip():
        return None

    from datetime import date, datetime
    root = Path(os.getenv("REPORTS_DIR", "./reports")).resolve()
    day_dir = root / date.today().isoformat()
    day_dir.mkdir(parents=True, exist_ok=True)

    # Filename: {agent}-{job_id}-{hhmm}.md to keep them sortable + unique
    now = datetime.now()
    safe_agent = agent_id.replace("/", "-")
    filename = f"{safe_agent}-{job_id:05d}-{now.strftime('%H%M')}.md"
    path = day_dir / filename

    # Build the markdown document
    lines = [
        f"# {agent_id} — Job #{job_id}",
        f"",
        f"**Status:** {status}",
        f"**Timestamp:** {now.isoformat()}",
        f"**Prompt:**",
        f"",
        f"> {prompt.strip()}",
        f"",
        f"---",
        f"",
        f"## Output",
        f"",
        output.strip(),
        f"",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")

    # Also copy to Obsidian vault if configured
    vault = os.getenv("OBSIDIAN_VAULT_PATH", "").strip()
    if vault:
        try:
            vault_dir = (Path(vault).expanduser() / "reports" / date.today().isoformat()).resolve()
            vault_dir.mkdir(parents=True, exist_ok=True)
            import shutil
            shutil.copy2(path, vault_dir / filename)
        except Exception as e:
            print(f"[artifacts] Failed to copy to vault: {e}")

    return path
